### ISSUE TITLE
Request: CSS Customization

### ISSUE THREAD

**Issue by cambiaresearch** [andrianvaleanu/WP-Maintenance-Mode#149]
It would be nice to allow custom CSS on the design tab which would be automatically injected into the layout.

But short of that, can we just change the CSS classes in the HTML to be more specific so that we could add CSS elsewhere in our site or theme and not have to worry about a conflict.

The body tag has a *background* class and the div enclosing all the text has a *wrap* class.  These names are both very likely to create conflicts when not in maintenance mode.

![capture](https://cloud.githubusercontent.com/assets/20992509/20042335/04ad0650-a43e-11e6-8855-2f86e2ddd2c5.JPG)

I would propose the following simple change which would then allow conflict free CSS hooks:

    <body class="background wpmm-background">
       <div class="wrap wpmm-wrap">
          ...

**Comment by georgejipa** [comment]
The CSS for maintenance mode page has nothing to do with the css of your theme. So... you can use any class name you want.

**Comment by cambiaresearch** [comment]
OK.  I was thinking that the stylesheets for the site would still be on the page, but in checking I see that they are not.

That leaves us, therefore, with only my first option:  add custom CSS support to the plugin for injecting your own CSS.  This could be a simple textarea on the design tab.

I already tried adding a style section <style></style> in the editor, it got stripped out.

**Comment by georgejipa** [comment]
The next version will have a custom css section and will be released in a week or two. :)

**Comment by cambiaresearch** [comment]
Awesome!  It's a great little plugin.

**Comment by georgejipa** [comment]
Before the release... you can add custom css by using `wpmm_head` hook. I know it is a little bit complicated, but works great.

```
// place it in functions.php of your active theme
add_action('wpmm_head', 'wpmm_custom_css');

function wpmm_custom_css(){
 // the css you need 
 echo '<style>
       .background { background-size: contain !important; }
       </style>';
}
````

**Comment by BossOz** [comment]
any news on this?

**Comment by edgariscoding** [comment]
Is the CSS customization supposed to be in the latest version?

**Comment by danielaebel** [comment]
Any news here?

**Comment by georgejipa** [comment]
@danielaebel it will be available in v2.3.0.

**Comment by WillPresley** [comment]
Hey @georgejipa I just installed 2.3.0 after SeedProd ruined their plugin and I'm not seeing the Custom CSS area anywhere. I'll look for a PR that I can possibly help with too but thanks for the hook!

**Comment by georgejipa** [comment]
@WillPresley We postponed the Custom CSS setting multiple times, but we will add it as soon as we find some free time.

Until then, you can also use the `wpmm_styles` filter: https://github.com/WP-Maintenance-Mode/Snippet-Library/blob/master/enqueue-css-files.php

**Comment by georgejipa** [comment]
We added the Custom CSS setting in v2.4.0.
