### ISSUE TITLE
Mobile device (atleast iphone) not working properly

### ISSUE THREAD

**Issue by Thug0416** [andrianvaleanu/WP-Maintenance-Mode#222]
Hi i downloaded the wp-maintenance plugin for wordpress and i got a good coming soon page.

Atleast thats what i thought after checking the normal browsers on my laptop. But after checking it on my iphone the subscribe button was not working properly. Atleast it was different (the shape) than it was on my laptop.

this is the link:

https://www.ricciwee.com

**Comment by Thug0416** [comment]
![1](https://user-images.githubusercontent.com/41521622/66937536-e8bfca80-f03f-11e9-8d5e-64d5ffd8bd9f.PNG)


![Onderhoudsmodus](https://user-images.githubusercontent.com/41521622/66937614-0c831080-f040-11e9-8f44-25a01fb9ffbe.png)

As you can see the second image, which is taken from my iphone, the subsscribe button is not working right. It was a different shape and there is some grey in it. Also the word "subscribe" is not in the middle.

Any idea how I can fix this?

**Comment by georgejipa** [comment]
Right now, I don't have an iPhone to make tests, but I'll try to add a patch in the next release. No ETA though.

**Comment by Thug0416** [comment]
The second imagine is from Safari yes. But it seems to be the same in Google Chrome. I just tested

**Comment by Thug0416** [comment]
I was wondering if you guys could tell me where I what file I can find the sourcode of this subscribe button. I have plugin editor infront of me. I just need to know where I can find this part so i can try to look it up for myself and adjust it. I would love to get it fixed ASAP.

**Comment by georgejipa** [comment]
Thank you.

If you have the necessary skills, you can try to solve it yourself.

- CSS: `/wp-content/plugins/wp-maintenance-mode/assets/css/style.min.css`
- HTML: `/wp-content/plugins//wp-maintenance-mode/views/maintenance.php`

**Comment by Thug0416** [comment]
I couldnt solve it myself unfortunately. Any idea on when the next release will come out? Aprrox?

**Comment by georgejipa** [comment]
Next month.

Try to add this snippet at the end of `style.min.css`:

```css
.wrap form.subscribe_form input[type=submit] {
	border-radius: 0 !important;
	-webkit-appearance: none !important;
}

@media only screen and (max-width: 550px) {
	.wrap div.subscribe_border {
		width: 95% !important;
	}
}
````

**Comment by Thug0416** [comment]
fixed! tyvm for you time and effort! also very nice you reply so fast

once again thanks!
