### ISSUE TITLE
The maintenance mode does not work..

### ISSUE THREAD

**Issue by N4good** [andrianvaleanu/WP-Maintenance-Mode#244]
Hello, 
When I activate the maintenance mode on belgiebox.be. It does not work... Could you know why? 
Thank you a lot!

**Comment by georgejipa** [comment]
Hello @N4good,

Do you use a cache plugin or a service like Cloudflare? If yes, purge the cache after you activate/deactivate the maintenance mode.

---
George

**Comment by N4good** [comment]
Indeed thank you!!
Have you received the BAT tip? First time I see it :)

**Comment by georgejipa** [comment]
@N4good You're welcome. Could you please tell me what BAT means? :)

**Comment by N4good** [comment]
BAT for Basic Attention Token. You should check it out, Brave is a very interesting web browser ;)

**Comment by georgejipa** [comment]
Oh, thank you. I will take a look.
