### ISSUE TITLE
Check if maintenant mode activated in PHP

### ISSUE THREAD

**Issue by cedriccharles4** [andrianvaleanu/WP-Maintenance-Mode#254]
Hello there :) !

First of all thank you for your plugin.

I would love to check if the plugin is activated in PHP (to do some PHP stuffs).
Is there a function/hook to check this?

Kind regards,
Cedric

**Comment by georgejipa** [comment]
Hello @cedriccharles4,

1. If you want to check if the plugin is active, you can use the [is_plugin_active](https://developer.wordpress.org/reference/functions/is_plugin_active/) function. 

```php
is_plugin_active('wp-maintenance-mode/wp-maintenance-mode.php');
```

2. If you want to see if check if the maintenance mode is activated or not, you can use:

```php
$options = get_option('wpmm_settings', array());

if (isset($options['general']['status']) && $options['general']['status'] === 1) {
    echo 'Maintenance Mode Status: activated';
} else {
    echo 'Maintenance Mode Status: deactivated';
}
```

---
George

**Comment by cedriccharles4** [comment]
Hi @georgejipa !

Thank you for your answer :) Ive managed to do it like that (just before you answer me :
`// ***********************************************************************************
// ******* Check if WP Maintenance Mode is available and activated
// ***********************************************************************************
function is_wpmm_activated() {
	if (!class_exists('WP_Maintenance_Mode')) {
		return false;
	}

	// get settings
	$wpmm_settings = WP_Maintenance_Mode::get_instance()->get_plugin_settings();
	$wpmm_status = $wpmm_settings['general']['status'];
	if($wpmm_status) {
		return true;
	} else {
		return false;
	}
}`

I think this is correct, right?

Thank you :)

**Comment by georgejipa** [comment]
Yes, it's just another way to do it. :)

**Comment by cedriccharles4** [comment]
Cool, perfect :) ! Thank you !
