### ISSUE TITLE
Maintenance mode does not work while database is down

### ISSUE THREAD

**Issue by msm-mdmahbubur-rahman** [andrianvaleanu/WP-Maintenance-Mode#259]
We have our WP blog site hosted in AWS cloud and using this plugin.
Sometimes we need to recover our database from the previous snapshot.

While DB creation is in progress, WordPress cannot connect to the database because a new DB is being created and the old DB is being deleted. At this point in time, this plugin does not work. 

When the site is accessed (Either admin user or normal user/visitor), WordPress says "Database connection error"

It means if we update or production database, the user will face downtime problem which is not expected.

**Comment by georgejipa** [comment]
@msm-mdmahbubur-rahman Of course, it is not working. If WordPress can't connect to the database, the regular & must-use plugins are not loaded. To conclude: there is nothing to fix.

For your case scenario, you should search about the `db-error.php` drop-in.

**Comment by msm-mdmahbubur-rahman** [comment]
Thanks for the feedback
