### ISSUE TITLE
Site with 2 domain names/languages : How to activate WP maintenance on 1 single domain name?

### ISSUE THREAD

**Issue by spip93** [andrianvaleanu/WP-Maintenance-Mode#260]
Hi,

I manage a Wordpress site for a client. This site is in 2 languages with one domain name per language.
My client would like to enable maintenance mode for only 1 language / domain name.
Is it possible ? If yes, how ?

Thank you for your reply.

Have a good day

**Comment by georgejipa** [comment]
Hello @spip93,

Technically, it's just one WordPress website, so it's not possible to do it by default. 

But if you have experience with WordPress hooks, you can try to use the `wpmm_is_excluded` hook. Here's an example: https://github.com/WP-Maintenance-Mode/Snippet-Library/blob/7fcc025fc2228d0ac8a14f37f87a69d6f9aeddcd/exclude-visitors-from-maintenance-mode.php#L87
