### ISSUE TITLE
Use a custom page on WPMM

### ISSUE THREAD

**Issue by maitre-hibou** [andrianvaleanu/WP-Maintenance-Mode#264]
Hey there,

I created a maintenance page with Divi Builder, and I would like to use it instead of the content provided by the plugin.

Is there something I can hook maybe ?

Thanks !

**Comment by georgejipa** [comment]
Hello,

You can override the [default maintenance mode template](https://github.com/andrianvaleanu/WP-Maintenance-Mode/blob/master/views/maintenance.php), but you can't use a page created with Divi (instead of the maintenance mode template) without customizing the way the plugin works.

--
George
